export enum Role {
  WARD = 'WARD',
  DISTRICT = 'DISTRICT',
  VHTT = 'VHTT',
}

export enum PositionStatus {
  ACTIVE = 'ACTIVE',
  IN_PROGRESS = 'IN_PROGRESS',
  DEACTIVE = 'DEACTIVE',
  NOT_YET = 'NOT_YET',
}

export enum LocationType {
  PUBLIC_LAND = 'PUBLIC_LAND',
  PRIVATE_LAND = 'PRIVATE_LAND',
  SHOPPING_CENTER = 'SHOPPING_CENTER',
  HOUSE = 'HOUSE',
  MARKET = 'MARKET',
  GAS_STATION = 'GAS_STATION',
  PARK = 'PARK',
  BUS_SHELTER = 'BUS_SHELTER',
}
